export const countryFlags: Record<string, string> = {
  'USA': '🇺🇸', 'United States': '🇺🇸',
  'GBR': '🇬🇧', 'UK': '🇬🇧', 'Great Britain': '🇬🇧', 'England': '🇬🇧',
  'ESP': '🇪🇸', 'Spain': '🇪🇸',
  'FRA': '🇫🇷', 'France': '🇫🇷',
  'GER': '🇩🇪', 'Germany': '🇩🇪',
  'ITA': '🇮🇹', 'Italy': '🇮🇹',
  'SRB': '🇷🇸', 'Serbia': '🇷🇸',
  'RUS': '🇷🇺', 'Russia': '🇷🇺',
  'AUS': '🇦🇺', 'Australia': '🇦🇺',
  'CAN': '🇨🇦', 'Canada': '🇨🇦',
  'CHN': '🇨🇳', 'China': '🇨🇳',
  'JPN': '🇯🇵', 'Japan': '🇯🇵',
  'IND': '🇮🇳', 'India': '🇮🇳',
  'BRA': '🇧🇷', 'Brazil': '🇧🇷',
  'NZL': '🇳🇿', 'New Zealand': '🇳🇿',
  'SUI': '🇨🇭', 'Switzerland': '🇨🇭',
  'ARG': '🇦🇷', 'Argentina': '🇦🇷',
  'POL': '🇵🇱', 'Poland': '🇵🇱',
  'BEL': '🇧🇪', 'Belgium': '🇧🇪',
  'NED': '🇳🇱', 'Netherlands': '🇳🇱',
  'CZE': '🇨🇿', 'Czech Republic': '🇨🇿',
  'GRE': '🇬🇷', 'Greece': '🇬🇷',
  'HUN': '🇭🇺', 'Hungary': '🇭🇺',
  'ROU': '🇷🇴', 'Romania': '🇷🇴',
  'CRO': '🇭🇷', 'Croatia': '🇭🇷',
  'KAZ': '🇰🇿', 'Kazakhstan': '🇰🇿',
  'UKR': '🇺🇦', 'Ukraine': '🇺🇦',
  'POR': '🇵🇹', 'Portugal': '🇵🇹',
  'GEO': '🇬🇪', 'Georgia': '🇬🇪',
  'SVK': '🇸🇰', 'Slovakia': '🇸🇰',
  'SVN': '🇸🇮', 'Slovenia': '🇸🇮',
  'AUT': '🇦🇹', 'Austria': '🇦🇹',
  'PER': '🇵🇪', 'Peru': '🇵🇪',
  'MEX': '🇲🇽', 'Mexico': '🇲🇽',
  'COL': '🇨🇴', 'Colombia': '🇨🇴',
  'CHI': '🇨🇱', 'Chile': '🇨🇱',
  'ECU': '🇪🇨', 'Ecuador': '🇪🇨',
  'KOR': '🇰🇷', 'South Korea': '🇰🇷',
  'THA': '🇹🇭', 'Thailand': '🇹🇭',
  'MAS': '🇲🇾', 'Malaysia': '🇲🇾',
  'IDN': '🇮🇩', 'Indonesia': '🇮🇩',
  'PHL': '🇵🇭', 'Philippines': '🇵🇭',
  'PAK': '🇵🇰', 'Pakistan': '🇵🇰',
  'TUR': '🇹🇷', 'Turkey': '🇹🇷',
  'ZA': '🇿🇦', 'South Africa': '🇿🇦',
}

export function getCountryFlag(countryCode: string | undefined): string {
  if (!countryCode) return '🌍'
  return countryFlags[countryCode] || countryFlags[countryCode?.toUpperCase()] || '🌍'
}
