export const playerCountries: Record<string, string> = {
  // ── ATP Top 100 ───────────────────────────────────────────
  'Jannik Sinner': 'ITA', 'Novak Djokovic': 'SRB', 'Carlos Alcaraz': 'ESP',
  'Alexander Zverev': 'GER', 'Taylor Fritz': 'USA', 'Casper Ruud': 'NOR',
  'Daniil Medvedev': 'RUS', 'Tommy Paul': 'USA', 'Andrey Rublev': 'RUS',
  'Holger Rune': 'DEN', 'Stefanos Tsitsipas': 'GRE', 'Grigor Dimitrov': 'BUL',
  'Alex de Minaur': 'AUS', 'Ugo Humbert': 'FRA', 'Lorenzo Musetti': 'ITA',
  'Hubert Hurkacz': 'POL', 'Arthur Fils': 'FRA', 'Frances Tiafoe': 'USA',
  'Felix Auger-Aliassime': 'CAN', 'Sebastian Korda': 'USA', 'Ben Shelton': 'USA',
  'Karen Khachanov': 'RUS', 'Nicolas Jarry': 'CHI', 'Alejandro Davidovich Fokina': 'ESP',
  'Tallon Griekspoor': 'NED', 'Matteo Arnaldi': 'ITA', 'Alexander Bublik': 'KAZ',
  'Tomas Machac': 'CZE', 'Jiri Lehecka': 'CZE', 'Nuno Borges': 'POR',
  'Francisco Cerundolo': 'ARG', 'Sebastián Báez': 'ARG', 'Rafael Nadal': 'ESP',
  'Roger Federer': 'SUI', 'Andy Murray': 'GBR', 'Dominic Thiem': 'AUT',
  'Matteo Berrettini': 'ITA', 'Cameron Norrie': 'GBR', 'Denis Shapovalov': 'CAN',
  'Brandon Nakashima': 'USA', 'Botic van de Zandschulp': 'NED', 'Roberto Bautista Agut': 'ESP',
  'Pablo Carreno Busta': 'ESP', 'Albert Ramos-Vinolas': 'ESP', 'David Goffin': 'BEL',
  'Gael Monfils': 'FRA', 'Jan-Lennard Struff': 'GER', 'Fabian Marozsan': 'HUN',
  'Laslo Djere': 'SRB', 'Giovanni Mpetshi Perricard': 'FRA', 'Thanasi Kokkinakis': 'AUS',
  'Alex Michelsen': 'USA', 'Jakub Mensik': 'CZE', 'Stan Wawrinka': 'SUI',
  'Marcos Giron': 'USA', 'Miomir Kecmanovic': 'SRB', 'Mariano Navone': 'ARG',
  'Daniel Evans': 'GBR', 'Jack Draper': 'GBR', 'Liam Broady': 'GBR',
  'Andy Murray': 'GBR', 'Billy Harris': 'GBR', 'Jacob Fearnley': 'GBR',
  'Jan Choinski': 'GBR', 'Henry Searle': 'GBR', 'Yoshihito Nishioka': 'JPN',
  'Taro Daniel': 'JPN', 'Yosuke Watanuki': 'JPN', 'Kei Nishikori': 'JPN',
  'Hiroshi Matsuoka': 'JPN', 'Shintaro Mochizuki': 'JPN',
  'Diego Schwartzman': 'ARG', 'Cristian Garin': 'CHI', 'Thiago Seyboth Wild': 'BRA',
  'Thiago Monteiro': 'BRA', 'Joao Fonseca': 'BRA', 'Joao Sousa': 'POR',
  'Bernabe Zapata Miralles': 'ESP', 'Pedro Cachin': 'ARG', 'Juan Pablo Varillas': 'PER',
  'Rinky Hijikata': 'AUS', 'Jordan Thompson': 'AUS', 'Christopher O\'Connell': 'AUS',
  'Alexei Popyrin': 'AUS', 'Max Purcell': 'AUS', 'James Duckworth': 'AUS',
  'Yannick Hanfmann': 'GER', 'Maximilian Marterer': 'GER', 'Oscar Otte': 'GER',
  'Daniel Altmaier': 'GER', 'Henri Squire': 'GER', 'Dominic Thiem': 'AUT',
  'Sebastian Ofner': 'AUT', 'Jurij Rodionov': 'AUT', 'Filip Misolic': 'AUT',
  'Richard Gasquet': 'FRA', 'Adrian Mannarino': 'FRA', 'Corentin Moutet': 'FRA',
  'Gregoire Barrere': 'FRA', 'Manuel Guinard': 'FRA', 'Quentin Halys': 'FRA',
  'Hugo Gaston': 'FRA', 'Luca Van Assche': 'FRA', 'Maxime Cressy': 'FRA',
  'Christopher Eubanks': 'USA', 'Emilio Nava': 'USA', 'Reilly Opelka': 'USA',
  'Denis Kudla': 'USA', 'Aleksandar Kovacevic': 'USA', 'Learner Tien': 'USA',
  'Nicola Kuhn': 'ESP', 'Roberto Carballes Baena': 'ESP', 'Pedro Martinez': 'ESP',
  'Jaume Munar': 'ESP', 'Marc-Andrea Huesler': 'SUI', 'Dominic Stricker': 'SUI',
  'Leandro Riedi': 'SUI', 'Quentin Halys': 'FRA', 'Alexandre Muller': 'FRA',
  'Dusan Lajovic': 'SRB', 'Filip Krajinovic': 'SRB', 'Hamad Medjedovic': 'SRB',
  'Roman Safiullin': 'RUS', 'Pavel Kotov': 'RUS', 'Mikhail Kukushkin': 'KAZ',
  'Timofei Skatov': 'KAZ', 'Alexander Shevchenko': 'KAZ', 'Borna Coric': 'CRO',
  'Marin Cilic': 'CRO', 'Borna Gojo': 'CRO', 'Duje Ajdukovic': 'CRO',
  'Pedro Sousa': 'POR', 'Gastao Elias': 'POR', 'Tomas Barrios Vera': 'CHI',
  'Alejandro Tabilo': 'CHI', 'Luciano Darderi': 'ITA', 'Flavio Cobolli': 'ITA',
  'Luca Nardi': 'ITA', 'Andrea Vavassori': 'ITA', 'Mattia Bellucci': 'ITA',
  'Stefano Travaglia': 'ITA', 'Marco Cecchinato': 'ITA', 'Fabio Fognini': 'ITA',
  'Yibing Wu': 'CHN', 'Zhizhen Zhang': 'CHN', 'Juncheng Shang': 'CHN',
  'Jiri Vesely': 'CZE', 'Adam Pavlasek': 'CZE', 'Zdenek Kolar': 'CZE',
  'Vasek Pospisil': 'CAN', 'Gabriel Diallo': 'CAN', 'Alexis Galarneau': 'CAN',
  'Juan Manuel Cerundolo': 'ARG', 'Federico Coria': 'ARG', 'Camilo Ugo Carabelli': 'ARG',
  'Nicolas Kicker': 'ARG', 'Tomas Martin Etcheverry': 'ARG', 'Facundo Diaz Acosta': 'ARG',
  'Nicolás Álvarez Varona': 'ESP', 'David Pichler': 'AUT',
  'Aleksandar Vukic': 'AUS', 'Adam Walton': 'AUS', 'Tristan Schoolkate': 'AUS',
  'Arthur Cazaux': 'FRA', 'Anthony Moutet': 'FRA',
  'Nicolas Mahut': 'FRA', 'Edouard Roger-Vasselin': 'FRA',
  'Jiří Lehečka': 'CZE', 'Dalibor Svrcina': 'CZE',
  'Roberto Agut': 'ESP', 'Feliciano Lopez': 'ESP', 'Fernando Verdasco': 'ESP',
  'Albert Ramos': 'ESP', 'Marc Lopez': 'ESP',
  'Andreas Seppi': 'ITA', 'Simone Bolelli': 'ITA', 'Thomas Fabbiano': 'ITA',
  'Victor Estrella Burgos': 'DOM', 'Orlando Luz': 'BRA', 'Felipe Meligeni': 'BRA',
  'Emilio Gomez': 'ECU', 'Gonzalo Gomez': 'ECU',
  'Guido Andreozzi': 'ARG', 'Leonardo Mayer': 'ARG', 'Horacio Zeballos': 'ARG',
  'Damir Dzumhur': 'BIH', 'Mirza Basic': 'BIH',
  'Illya Marchenko': 'UKR', 'Sergiy Stakhovsky': 'UKR', 'Oleksii Krutykh': 'UKR',
  'Luca Struff': 'GER', 'Peter Gojowczyk': 'GER', 'Philipp Kohlschreiber': 'GER',
  'James Ward': 'GBR', 'Marcus Willis': 'GBR', 'Kyle Edmund': 'GBR',
  'Gilles Simon': 'FRA', 'Jo-Wilfried Tsonga': 'FRA', 'Benoit Paire': 'FRA',
  'Lucas Pouille': 'FRA', 'Jeremy Chardy': 'FRA',
  'Nikoloz Basilashvili': 'GEO', 'Aleksandre Metreveli': 'GEO',
  'Marcos Baghdatis': 'CYP', 'Christos Tsitsipas': 'GRE',
  'Tennys Sandgren': 'USA', 'Jack Sock': 'USA', 'John Isner': 'USA',
  'Sam Querrey': 'USA', 'Mardy Fish': 'USA', 'Andy Roddick': 'USA',
  'Gilles Muller': 'LUX', 'Ivo Karlovic': 'CRO',
  'Radek Stepanek': 'CZE', 'Lukas Rosol': 'CZE', 'Jiri Novak': 'CZE',
  'Tommy Haas': 'GER', 'Michael Kohlmann': 'GER',
  'Robin Soderling': 'SWE', 'Thomas Enqvist': 'SWE',
  'Marton Fucsovics': 'HUN', 'Attila Balazs': 'HUN',
  'Laslo Djere': 'SRB', 'Viktor Troicki': 'SRB', 'Janko Tipsarevic': 'SRB',
  'Nicolas Almagro': 'ESP', 'Tommy Robredo': 'ESP', 'David Ferrer': 'ESP',
  'Mario Ancic': 'CRO', 'Ivan Dodig': 'CRO', 'Antonio Veic': 'CRO',
  'Igor Sijsling': 'NED', 'Robin Haase': 'NED', 'Thiemo de Bakker': 'NED',
  'Tobias Kamke': 'GER', 'Benjamin Becker': 'GER', 'Simon Greul': 'GER',
  'Paul-Henri Mathieu': 'FRA', 'Stephane Robert': 'FRA', 'Julien Benneteau': 'FRA',
  'Edouard Roger Vasselin': 'FRA', 'Florent Serra': 'FRA', 'Michael Llodra': 'FRA',
  'Santiago Giraldo': 'COL', 'Alejandro Gonzalez': 'COL',
  'Horacio Zeballos': 'ARG', 'Eduardo Schwank': 'ARG',
  'Guido Pella': 'ARG', 'Federico Delbonis': 'ARG', 'Juan Ignacio Londero': 'ARG',
  'Radu Albot': 'MDA', 'Victor Vlad Cornea': 'ROU', 'Marius Copil': 'ROU',
  'Adrian Ungur': 'ROU', 'Florin Mergea': 'ROU',
  'Mikhail Youzhny': 'RUS', 'Igor Andreev': 'RUS', 'Teimuraz Gabashvili': 'RUS',
  'Evgeny Donskoy': 'RUS', 'Konstantin Kravchuk': 'RUS', 'Aslan Karatsev': 'RUS',
  'Andrei Vasilevski': 'BLR', 'Ilya Ivashka': 'BLR', 'Egor Gerasimov': 'BLR',
  'Dmitry Popko': 'KAZ', 'Mikhail Kukushkin': 'KAZ', 'Dmitry Makeyev': 'KAZ',
  'Lamine Ouahab': 'ALG', 'Malek Jaziri': 'TUN', 'Mohamed Safwat': 'EGY',
  'Elias Ymer': 'SWE', 'Mikael Ymer': 'SWE', 'Thomas Johansson': 'SWE',
  'Nicolás Barrientos': 'COL',
  'Nishesh Basavareddy': 'USA', 'Cooper Williams': 'USA', 'William Manning': 'USA',
  'Garrett Sams': 'USA', 'Collin Altamirano': 'USA', 'Nathaniel Lammons': 'USA',
  'Toby Mayo': 'GBR', 'Anton Mayo': 'USA',
  'Andreas Mayo': 'AUT', 'George Hussey': 'AUS',
  'Adam Walton': 'AUS', 'Dayne Kelly': 'AUS',
  'Daniel Glinka': 'GER', 'Max Glinka': 'GER', 'Jonas Glinka': 'GER',

  // ── WTA Top 100 ───────────────────────────────────────────
  'Iga Swiatek': 'POL', 'Aryna Sabalenka': 'BLR', 'Coco Gauff': 'USA',
  'Elena Rybakina': 'KAZ', 'Jessica Pegula': 'USA', 'Madison Keys': 'USA',
  'Mirra Andreeva': 'RUS', 'Emma Navarro': 'USA', 'Jasmine Paolini': 'ITA',
  'Karolina Muchova': 'CZE', 'Daria Kasatkina': 'RUS', 'Paula Badosa': 'ESP',
  'Barbora Krejcikova': 'CZE', 'Qinwen Zheng': 'CHN', 'Marketa Vondrousova': 'CZE',
  'Emma Raducanu': 'GBR', 'Danielle Collins': 'USA', 'Anna Kalinskaya': 'RUS',
  'Liudmila Samsonova': 'RUS', 'Elina Svitolina': 'UKR', 'Beatriz Haddad Maia': 'BRA',
  'Maria Sakkari': 'GRE', 'Donna Vekic': 'CRO', 'Caroline Wozniacki': 'DEN',
  'Jelena Ostapenko': 'LAT', 'Anastasia Pavlyuchenkova': 'RUS', 'Wang Xinyu': 'CHN',
  'Xinyu Wang': 'CHN', 'Linda Noskova': 'CZE', 'Yulia Putintseva': 'KAZ',
  'Elise Mertens': 'BEL', 'Sorana Cirstea': 'ROU', 'Magdalena Frech': 'POL',
  'Dayana Yastremska': 'UKR', 'Victoria Azarenka': 'BLR', 'Petra Kvitova': 'CZE',
  'Karolina Pliskova': 'CZE', 'Veronika Kudermetova': 'RUS', 'Sloane Stephens': 'USA',
  'Serena Williams': 'USA', 'Venus Williams': 'USA', 'Naomi Osaka': 'JPN',
  'Simona Halep': 'ROU', 'Ashleigh Barty': 'AUS', 'Bianca Andreescu': 'CAN',
  'Sofia Kenin': 'USA', 'Garbine Muguruza': 'ESP', 'Anett Kontaveit': 'EST',
  'Ons Jabeur': 'TUN', 'Belinda Bencic': 'SUI', 'Anastasia Potapova': 'RUS',
  'Diana Shnaider': 'RUS', 'Leylah Fernandez': 'CAN', 'Amanda Anisimova': 'USA',
  'Bernarda Pera': 'USA', 'Marie Bouzkova': 'CZE', 'Katerina Siniakova': 'CZE',
  'Nadia Podoroska': 'ARG', 'Tamara Zidansek': 'SLO', 'Ajla Tomljanovic': 'AUS',
  'Alicia Parks': 'USA', 'Magda Linette': 'POL', 'Irina Begu': 'ROU',
  'Elena-Gabriela Ruse': 'ROU', 'Ana Bogdan': 'ROU', 'Jaqueline Cristian': 'ROU',
  'Viktoriya Tomova': 'BUL', 'Sara Sorribes Tormo': 'ESP', 'Rebecca Marino': 'CAN',
  'Harriet Dart': 'GBR', 'Francesca Jones': 'GBR', 'Katie Boulter': 'GBR',
  'Heather Watson': 'GBR', 'Jodie Burrage': 'GBR', 'Laura Robson': 'GBR',
  'Anna Blinkova': 'RUS', 'Vera Zvonareva': 'RUS', 'Natalya Vikhlyantseva': 'RUS',
  'Ekaterina Alexandrova': 'RUS', 'Anna Kalinskaya': 'RUS',
  'Zhu Lin': 'CHN', 'Wang Yafan': 'CHN', 'Zhang Shuai': 'CHN',
  'Peng Shuai': 'CHN', 'Han Xinyun': 'CHN', 'Zheng Saisai': 'CHN',
  'Kurumi Nara': 'JPN', 'Misaki Doi': 'JPN', 'Nao Hibino': 'JPN',
  'Moyuka Uchijima': 'JPN', 'Ena Shibahara': 'JPN',
  'Arantxa Rus': 'NED', 'Richel Hogenkamp': 'NED',
  'Anhelina Kalinina': 'UKR', 'Marta Kostyuk': 'UKR', 'Lesia Tsurenko': 'UKR',
  'Kateryna Baindl': 'UKR', 'Katarina Zavatska': 'UKR',
  'Varvara Gracheva': 'RUS', 'Kamilla Rakhimova': 'RUS',
  'Alize Cornet': 'FRA', 'Fiona Ferro': 'FRA', 'Clara Burel': 'FRA',
  'Oceane Dodin': 'FRA', 'Pauline Parmentier': 'FRA', 'Mathilde Johansson': 'FRA',
  'Cristina Bucsa': 'ESP', 'Nuria Parrizas Diaz': 'ESP', 'Rebeka Masarova': 'ESP',
  'Tamara Korpatsch': 'GER', 'Laura Siegemund': 'GER', 'Eva Lys': 'GER',
  'Angelique Kerber': 'GER', 'Andrea Petkovic': 'GER',
  'Tatjana Maria': 'GER', 'Mona Barthel': 'GER',
  'Petra Martic': 'CRO', 'Donna Vekic': 'CRO', 'Jana Fett': 'CRO',
  'Polona Hercog': 'SLO', 'Kaja Juvan': 'SLO',
  'Tereza Martincova': 'CZE', 'Petra Noskova': 'CZE',
  'Alison Riske': 'USA', 'Lauren Davis': 'USA', 'Shelby Rogers': 'USA',
  'Caroline Dolehide': 'USA', 'Peyton Stearns': 'USA', 'Robin Montgomery': 'USA',
  'Asia Muhammad': 'USA', 'Taylor Townsend': 'USA', 'Varvara Lepchenko': 'USA',
  'Katerina Baindl': 'UKR',
  'Ekaterina Makarova': 'RUS', 'Elena Vesnina': 'RUS',
  'Yaroslava Shvedova': 'KAZ', 'Zarina Diyas': 'KAZ',
  'Galina Voskoboeva': 'KAZ', 'Sesil Karatantcheva': 'KAZ',
  'Timea Bacsinszky': 'SUI', 'Viktoriya Golubic': 'SUI', 'Stefanie Voegele': 'SUI',
  'Jil Teichmann': 'SUI',
  'Kaia Kanepi': 'EST', 'Reka Luca Jani': 'HUN',
  'Sara Errani': 'ITA', 'Camila Giorgi': 'ITA', 'Lucia Bronzetti': 'ITA',
  'Martina Trevisan': 'ITA', 'Elisabetta Cocciaretto': 'ITA',
  'Monica Puig': 'PUR', 'Genie Bouchard': 'CAN', 'Eugenie Bouchard': 'CAN',
  'Sharon Fichman': 'CAN', 'Carol Zhao': 'CAN', 'Françoise Abanda': 'CAN',
  'Lucie Safarova': 'CZE', 'Renata Voracova': 'CZE', 'Klara Koukalova': 'CZE',
  'Alycia Parks': 'USA',
  'Danielle Vidmanova': 'CZE', 'D. Vidmanova': 'CZE',
  'Xiyu Wang': 'CHN',
}

export function getPlayerCountry(playerName: string): string | null {
  if (!playerName) return null

  // 1. Direct full-name match
  if (playerCountries[playerName]) return playerCountries[playerName]

  // 2. Abbreviated name match: "L. Broady" → match last name "Broady"
  const parts = playerName.trim().split(' ')
  if (parts.length >= 2) {
    const lastName = parts[parts.length - 1]
    const firstInitial = parts[0].replace('.', '')
    for (const [fullName, country] of Object.entries(playerCountries)) {
      const fp = fullName.split(' ')
      const fLast = fp[fp.length - 1]
      const fFirst = fp[0]
      if (fLast === lastName && fFirst.startsWith(firstInitial)) {
        return country
      }
    }
    // 3. Last-name-only fallback
    for (const [fullName, country] of Object.entries(playerCountries)) {
      if (fullName.split(' ').pop() === lastName) return country
    }
  }

  return null
}
